name = "ruwt"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-11-06"


[assets]
directory = ".svelte-kit/output/client"
binding = "ASSETS"

# D1 (relational DB)
[[d1_databases]]
binding = "DB"         # env.DB
database_name = "ruwt"
database_id = "5e08f725-146d-4f45-9ad3-7a438bafd665"

# KV (fast config/cache/session)
[[kv_namespaces]]
binding = "KV"
id = "9ab69c3234ee4a6fb103e39c7abdc79c"

# R2 (files/images)
[[r2_buckets]]
binding = "R2"
bucket_name = "ruwt"

## Queues (background jobs, optional)
#[[queues.producers]]
#binding = "JOBS"
#queue = "ruwt"
